python -m tasks.new_task First message...
python -m tasks.new_task Second message..
python -m tasks.new_task Third message...
python -m tasks.new_task Fourth message..
python -m tasks.new_task Fifth message.....
python -m tasks.new_task Sixth message..
